name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build -t georgemclaughlin/reddit_posts_server:${{ github.sha }} \
                     -t georgemclaughlin/reddit_posts_server:latest \
                     -t us.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/reddit_posts_server:${{ github.sha }} \
                     -t us.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/reddit_posts_server:latest \
                     .
        docker push georgemclaughlin/reddit_posts_server
        
    - uses: actions-hub/gcloud@272.0.0
      env:
        PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with: 
        args: |
          auth configure-docker
          docker push us.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/reddit_posts_server