name: Docker Image CI and CD

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set login for Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Tag Image, push to Docker Hub
      run: |
        docker build -t georgemclaughlin/reddit_posts_server:${{ github.sha }} \
                     -t georgemclaughlin/reddit_posts_server:latest \
                     -t us.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/reddit_posts_server:${{ github.sha }} \
                     -t us.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/reddit_posts_server:latest \
                     .
        docker push georgemclaughlin/reddit_posts_server
        
    - name: Set gcloud credentials and push to Google Container Registry
      uses: actions-hub/gcloud@272.0.0
      env:
        PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with: 
        args: |
          auth configure-docker
          docker push us.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/reddit_posts_server
          
    - name: Deploy new Docker Image to Cloud Run
      uses: actions-hub/gcloud@272.0.0
      env:
        PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with: 
        args: |
          run deploy redditpostsserver \
          --image us.gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/reddit_posts_server:${{ github.sha }} \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated