name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - uses: actions-hub/gcloud@272.0.0
      with:
        PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - run: |
        docker build -t georgemclaughlin/reddit_posts_server:${{ github.sha }} -t georgemclaughlin/reddit_posts_server:latest .
        docker push georgemclaughlin/reddit_posts_server
        docker push us.gcr.io/reddit_posts_server
